## Data Cleaning

In [1]:
import numpy as np
import pandas as pd
import re

In [2]:
ch83dg = pd.read_csv('./data/ch83dg.csv')
ch83m = pd.read_csv('./data/ch83m.csv')
ch83pru = pd.read_csv('./data/ch83pru.csv')
ch83q = pd.read_csv('./data/ch83q.csv')
ch89dg = pd.read_csv('./data/CH89DG.csv')
ch89m = pd.read_csv('./data/ch89m.csv')
ch89pru = pd.read_csv('./data/ch89pru.csv')
ch89q = pd.read_csv('./data/ch89q.csv')
ch93pru = pd.read_csv('./data/ch93pru.csv')
ch93q = pd.read_csv('./data/ch93q.csv')
chtaim = pd.read_csv('./data/chtaim.csv')
chtaipru = pd.read_csv('./data/chtaipru.csv')
chtaiq = pd.read_csv('./data/chtaiq.csv')

In [3]:
ch89dg.head(3) 
# many cells with periods only, used as an NA/null. Need to replace. 
# empty column added at end, due to formatting from csv. Will drop.

,County,Sex,Xiang,D001,D002,D003,D004,D005,D006,D007,...,D158,D159,D160,D161,G001,G002,G003,G004,G005,
0,AA,M,1,.,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,NaN
1,AA,M,2,.,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,NaN
2,AA,M,3,.,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,NaN

In [4]:
def clean_header(df):
    '''fn should format all dataframes as described below'''
    df.columns = df.columns.str.lower()
    df.columns = df.columns.str.replace("-", "_").str.replace(" ", "").str.replace("__", "_")

    return df

In [5]:
# list of dataframes to edit and iterate over
df_list = [ch83dg,
ch83m,
ch83pru,
ch83q,
ch89dg,
ch89m,
ch89pru,
ch89q,
ch93pru,
ch93q,
chtaim,
chtaipru,
chtaiq]

In [6]:
[clean_header(i) for i in df_list];

In [7]:
ch83dg.columns # sanity check

Index(['county', 'sex', 'xiang', 'd001', 'd002', 'd003', 'd004', 'd005',
       'd006', 'd007',
       ...
       'd153', 'd154', 'd155', 'd156', 'd157', 'd158', 'd159', 'd160', 'd161',
       ''],
      dtype='object', length=151)

In [8]:
# regex used to replace all whitespace in cells with nothing. Then replace lonely periods with nothing.
[i.replace(to_replace=' ', value='', regex=True, inplace=True) for i in df_list]
[i.replace(to_replace='^\.$', value='', regex=True, inplace=True) for i in df_list]

[None, None, None, None, None, None, None, None, None, None, None, None, None]

In [9]:
# All cells imported as object type, casting to numeric for EDA later.
ch83dg = ch83dg.apply(pd.to_numeric, errors='ignore')
ch83m = ch83m.apply(pd.to_numeric, errors='ignore')
ch83pru = ch83pru.apply(pd.to_numeric, errors='ignore')
ch83q = ch83q.apply(pd.to_numeric, errors='ignore')
ch89dg = ch89dg.apply(pd.to_numeric, errors='ignore')
ch89m = ch89m.apply(pd.to_numeric, errors='ignore')
ch89pru = ch89pru.apply(pd.to_numeric, errors='ignore')
ch89q = ch89q.apply(pd.to_numeric, errors='ignore')
ch93pru = ch93pru.apply(pd.to_numeric, errors='ignore')
ch93q = ch93q.apply(pd.to_numeric, errors='ignore')
chtaim = chtaim.apply(pd.to_numeric, errors='ignore')
chtaipru = chtaipru.apply(pd.to_numeric, errors='ignore')
chtaiq = chtaiq.apply(pd.to_numeric, errors='ignore')

In [10]:
# drop empty column at end of each DF
ch83dg.drop(columns='',inplace=True)
ch83m.drop(columns='',inplace=True)
ch83pru.drop(columns='',inplace=True)
ch83q.drop(columns='',inplace=True)
ch89dg.drop(columns='',inplace=True)
ch89m.drop(columns='',inplace=True)
ch89pru.drop(columns='',inplace=True)
ch89q.drop(columns='',inplace=True)
ch93pru.drop(columns='',inplace=True)
ch93q.drop(columns='',inplace=True)
chtaim.drop(columns='',inplace=True)
chtaipru.drop(columns='',inplace=True)
chtaiq.drop(columns='',inplace=True)

In [11]:
# drop rows where there is no data in the row. Some rows have some empty cells, hence the thresholds.
ch83dg.dropna(thresh=100, inplace=True)
ch83m.dropna(thresh=20, inplace=True)
ch83pru.dropna(thresh=20, inplace=True)
ch83q.dropna(thresh=20, inplace=True)
ch89dg.dropna(thresh=100, inplace=True)
ch89m.dropna(thresh=100, inplace=True)
ch89pru.dropna(thresh=100, inplace=True)
ch89q.dropna(thresh=100, inplace=True)
ch93pru.dropna(thresh=20, inplace=True)
ch93q.dropna(thresh=100, inplace=True)
chtaim.dropna(thresh=100, inplace=True)
chtaipru.dropna(thresh=100, inplace=True)
chtaiq.dropna(thresh=100, inplace=True)

In [12]:
# sanity check. making sure we didn't drop every row.
[i.shape for i in df_list]

[(621, 151),
 (621, 72),
 (621, 65),
 (621, 61),
 (621, 170),
 (621, 123),
 (621, 111),
 (621, 251),
 (117, 22),
 (117, 111),
 (144, 122),
 (144, 103),
 (144, 122)]

In [13]:
ch83m.head(10) # sanity check. cursory glance at data cleaning efficacy.

,county,sex,xiang,m001,m002,m003,m004,m005,m006,m007,...,m086,m087,m088,m103,m104,m105,m106,m107,m113,m117
2,AA,M,3,3.67,72.03,124.01,143.89,14.87,97.10,80.00,...,15.59,NaN,NaN,14.44,NaN,18.36,10.61,7.75,4.13,0.00
5,AA,F,3,3.20,42.49,74.48,100.46,7.67,59.48,60.57,...,12.62,1.00,0.0,12.64,0.31,16.02,9.71,6.30,4.73,0.09
8,AA,T,3,3.44,57.26,99.25,122.17,11.27,78.29,70.28,...,14.11,NaN,NaN,13.54,NaN,17.19,10.16,7.03,4.43,0.04
11,AB,M,3,5.01,67.69,138.61,170.09,16.66,110.54,91.44,...,21.42,NaN,NaN,13.81,NaN,25.04,14.33,10.71,3.97,0.00
14,AB,F,3,3.84,51.36,101.97,127.78,8.83,65.11,80.46,...,19.69,1.75,0.4,11.57,0.37,19.19,11.97,7.22,3.75,0.00
17,AB,T,3,4.42,59.52,120.29,148.94,12.75,87.83,85.95,...,20.56,NaN,NaN,12.69,NaN,22.12,13.15,8.96,3.86,0.00
20,AC,M,3,3.97,77.18,118.00,146.22,15.07,104.73,78.25,...,11.74,NaN,NaN,9.09,NaN,19.86,11.52,8.34,3.35,0.00
23,AC,F,3,3.13,47.66,71.48,99.12,8.27,67.32,62.52,...,15.61,2.33,0.0,7.63,0.45,15.63,9.32,6.31,2.31,0.00
26,AC,T,3,3.55,62.42,94.74,122.67,11.67,86.03,70.39,...,13.68,NaN,NaN,8.36,NaN,17.75,10.42,7.33,2.83,0.00
29,BA,M,3,8.42,113.88,124.89,224.26,20.41,97.38,177.03,...,23.93,NaN,NaN,31.63,NaN,42.12,38.39,3.73,12.92,6.12

In [14]:
[i.to_csv(f"./cleaned_data/{i}.csv") for i in df_list]

ch83dg.to_csv(f"./cleaned_data/{i}.csv")
ch83m.to_csv(f"./cleaned_data/{i}.csv")
ch83pru.to_csv(f"./cleaned_data/{i}.csv")
ch83q.to_csv(f"./cleaned_data/{i}.csv")
ch89dg.to_csv(f"./cleaned_data/{i}.csv")
ch89m.to_csv(f"./cleaned_data/{i}.csv")
ch89pru.dropna(thresh=100, inplace=True)
ch89q.dropna(thresh=100, inplace=True)
ch93pru.dropna(thresh=20, inplace=True)
ch93q.dropna(thresh=100, inplace=True)
chtaim.dropna(thresh=100, inplace=True)
chtaipru.dropna(thresh=100, inplace=True)
chtaiq.dropna(thresh=100, inplace=True)

OSError: [Errno 63] File name too long: './cleaned_data/    county sex  xiang  d001  d002  d003 d004  d005  d006 d007  ...    d153  \\\n0       AA   M      1                                          ...           \n1       AA   M      2                                          ...           \n2       AA   M      3                                          ...           \n3       AA   F      1                                          ...           \n4       AA   F      2                                          ...           \n..     ...  ..    ...   ...   ...   ...  ...   ...   ...  ...  ...     ...   \n616     YA   F      2                                          ...           \n617     YA   F      3                                          ...           \n618     YA   T      1                                          ...           \n619     YA   T      2                                          ...           \n620     YA   T      3  2217  41.2  67.2  361  16.7  12.1  4.0  ...  0.0010   \n\n      d154   d155   d156   d157   d158   d159   d160   d161      \n0                                                           NaN  \n1                                                           NaN  \n2                                                           NaN  \n3                                                           NaN  \n4                                                           NaN  \n..     ...    ...    ...    ...    ...    ...    ...    ...  ..  \n616                                                         NaN  \n617                                                         NaN  \n618                                                         NaN  \n619                                                         NaN  \n620  0.165  0.183  0.054  1.176  0.001  0.031  0.001  0.024 NaN  \n\n[621 rows x 151 columns].csv'